Add autoplay video setting
liftoff-app/liftoff pull request #405
Opened 2023-07-15 11:24 UTC by jjcomer

Fixes #404 

This adds a setting to enable if videos should automatically start playing or not.

2023-07-15 22:07 UTC, zachatrocity approved these changes
LGTM

2023-07-15 23:35 UTC, shocklateboy92 requested changes
Can we not make the video preview suck for no reason?
If people want an option, let's give it to them. Else let's leave a good feature as is.

2023-07-16 10:06 UTC, jjcomer commented
@shocklateboy92 Fixed!

2023-07-16 15:11 UTC, shocklateboy92 approved these changes

2023-07-17 05:48 UTC, merged